mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("pub_priv_school_ls/", include("pub_priv_school_ls.urls")),
    path('admin/', admin.site.urls),
]

pub_priv_school_ls/urls.py
from django.urls import path, register_converter
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .converters import FloatConverter

register_converter(FloatConverter, 'float')

app_name = "pub_priv_school_ls"
urlpatterns = [
    path("" , views.index, name="index"),
    path("area/<str:loc>/" , views.area, name="area"),
    path("list/<str:radius>/<float:latitude>/<float:longitude>/<str:loc>/", views.list, name="list")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pub_priv_school_ls/models.py
from django.db import models

# Create your models here.

class School(models.Model):
    distance = models.FloatField(default=-1.0)
    school_name = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    school_type = models.CharField(max_length=200, default='a')
    state = models.CharField(max_length=5, default='a')
    adress = models.CharField(max_length=200, default='a')
    school_zip = models.IntegerField(default=0)
    
    kindergarten = models.FloatField(default=-1.0)
    first_grade = models.FloatField(default=-1.0)
    second_grade = models.FloatField(default=-1.0)
    third_grade = models.FloatField(default=-1.0)
    fourth_grade = models.FloatField(default=-1.0)
    fifth_grade = models.FloatField(default=-1.0)
    sixth_grade = models.FloatField(default=-1.0)
    seventh_grade = models.FloatField(default=-1.0)
    eighth_grade = models.FloatField(default=-1.0)
    
    kindergarten_male = models.FloatField(default=-1.0)
    first_grade_male = models.FloatField(default=-1.0)
    second_grade_male = models.FloatField(default=-1.0)
    third_grade_male = models.FloatField(default=-1.0)
    fourth_grade_male = models.FloatField(default=-1.0)
    fifth_grade_male = models.FloatField(default=-1.0)
    sixth_grade_male = models.FloatField(default=-1.0)
    seventh_grade_male = models.FloatField(default=-1.0)
    eighth_grade_male = models.FloatField(default=-1.0)
    
    kindergarten_female = models.FloatField(default=-1.0)
    first_grade_female = models.FloatField(default=-1.0)
    second_grade_female = models.FloatField(default=-1.0)
    third_grade_female = models.FloatField(default=-1.0)
    fourth_grade_female = models.FloatField(default=-1.0)
    fifth_grade_female = models.FloatField(default=-1.0)
    sixth_grade_female = models.FloatField(default=-1.0)
    seventh_grade_female = models.FloatField(default=-1.0)
    eighth_grade_female = models.FloatField(default=-1.0)
    
    hispanic_students = models.IntegerField(default=-1)
    white_students = models.IntegerField(default=-1)
    black_students = models.IntegerField(default=-1)
    asian_students = models.IntegerField(default=-1)
    hawaiian_students = models.IntegerField(default=-1)
    native_students = models.IntegerField(default=-1)
    multi_race_students = models.IntegerField(default=-1)
    
    
    def __str__(self):
        return self.school_name
    

pub_priv_school_ls/forms.py
from django import forms

class InputData(forms.Form):
    input_latitude = forms.DecimalField(max_digits=10, decimal_places=7)
    input_longitude = forms.DecimalField(max_digits=10, decimal_places=7)
    radius = forms.DecimalField(max_digits=4, decimal_places=2)

pub_priv_school_ls/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import InputData
from .distance_calc import calculate_distance
from .models import School
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    #this code is run after inputs are submitted which saves the input data
    places = ['Ak','AL','AR','AZ','CA','CO','CT','DC','DE','FL','GA','HI','IA','ID','IL',
              'IN','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
              'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT',
              'VT','VA','WA','WV','WI','WY']
    return render(request, "pub_priv_school_ls/index.html", {"places": places})

def area(request, loc):
    if request.method == "POST":
        form = InputData(request.POST)
        if form.is_valid():
            input_longitude = form.cleaned_data["input_longitude"]
            input_latitude = form.cleaned_data["input_latitude"]
            radius = form.cleaned_data["radius"]
            #updates distance for all the schools
            all_schools = School.objects.filter(state__contains=loc)
            for schools in all_schools:
                schools.distance = round(calculate_distance(float(input_latitude), float(input_longitude), float(schools.latitude), float(schools.longitude)), 2)
                schools.save()
            return redirect(reverse("pub_priv_school_ls:list", args=[radius,float(input_latitude), float(input_longitude), loc]))
    else:
        #creates empty form to be filled out
        form = InputData()
        
    places = ['Ak','AL','AR','AZ','CA','CO','CT','DC','DE','FL','GA','HI','IA','ID','IL',
              'IN','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
              'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT',
              'VT','VA','WA','WV','WI','WY']
    
    return render(request, "pub_priv_school_ls/state.html", {"form": form, 'loc':loc, 'places':places})
    
def list(request, radius, latitude, longitude, loc):
    #for the new location button
    if request.method == "POST":
        return redirect(reverse("pub_priv_school_ls:index"))
    
    #creates all the context which are then used in html request
    local_schools = School.objects.filter(state__contains=loc).filter(distance__lt=float(radius)).order_by("distance")
    num_schools = local_schools.count()
    int_schools(local_schools)
    
    #get context for totals for male students    
    total_kindergarten_m = sum(schools.kindergarten_male for schools in local_schools)
    total_first_m = sum(schools.first_grade_male for schools in local_schools)
    total_second_m = sum(schools.second_grade_male for schools in local_schools)
    total_third_m = sum(schools.third_grade_male for schools in local_schools)
    total_fourth_m = sum(schools.fourth_grade_male for schools in local_schools)
    total_fifth_m = sum(schools.fifth_grade_male for schools in local_schools)
    total_sixth_m = sum(schools.sixth_grade_male for schools in local_schools)
    total_seventh_m = sum(schools.seventh_grade_male for schools in local_schools)
    total_eighth_m = sum(schools.eighth_grade_male for schools in local_schools)
    
    adressable_market_m = total_kindergarten_m + total_first_m + total_second_m + total_third_m + total_fourth_m + total_fifth_m + total_sixth_m + total_seventh_m + total_eighth_m
    
    #get context for female students
    total_kindergarten_f = sum(schools.kindergarten_female for schools in local_schools)
    total_first_f = sum(schools.first_grade_female for schools in local_schools)
    total_second_f = sum(schools.second_grade_female for schools in local_schools)
    total_third_f = sum(schools.third_grade_female for schools in local_schools)
    total_fourth_f = sum(schools.fourth_grade_female for schools in local_schools)
    total_fifth_f = sum(schools.fifth_grade_female for schools in local_schools)
    total_sixth_f = sum(schools.sixth_grade_female for schools in local_schools)
    total_seventh_f = sum(schools.seventh_grade_female for schools in local_schools)
    total_eighth_f = sum(schools.eighth_grade_female for schools in local_schools)
    
    adressable_market_f = total_kindergarten_f + total_first_f + total_second_f + total_third_f + total_fourth_f+ total_fifth_f + total_sixth_f + total_seventh_f + total_eighth_f
    
    #get context for demographics 
    total_hisp = sum(schools.hispanic_students for schools in local_schools)
    total_whi = sum(schools.white_students for schools in local_schools)
    total_black = sum(schools.black_students for schools in local_schools)
    total_asian = sum(schools.asian_students for schools in local_schools)
    total_hawi = sum(schools.hawaiian_students for schools in local_schools)
    total_native = sum(schools.native_students for schools in local_schools)
    total_multi = sum(schools.multi_race_students for schools in local_schools)
    
    data = [total_hisp,total_whi,total_black,total_asian,total_hawi,total_native,total_multi]
    context = {"local_schools": local_schools, "latitude":latitude, "longitude":longitude,
        "num_schools": num_schools,
        "total_kindergarten_m": total_kindergarten_m, 
        "total_first_m": total_first_m,
        "total_second_m": total_second_m,
        "total_third_m": total_third_m,
        "total_fourth_m": total_fourth_m,
        "total_fifth_m": total_fifth_m,
        "total_sixth_m": total_sixth_m,
        "total_seventh_m": total_seventh_m,
        "total_eighth_m": total_eighth_m,
        "adressable_market_m": adressable_market_m,
        "total_kindergarten_f": total_kindergarten_f, 
        "total_first_f": total_first_f,
        "total_second_f": total_second_f,
        "total_third_f": total_third_f,
        "total_fourth_f": total_fourth_f,
        "total_fifth_f": total_fifth_f,
        "total_sixth_f": total_sixth_f,
        "total_seventh_f": total_seventh_f,
        "total_eighth_f": total_eighth_f,
        "adressable_market_f": adressable_market_f,
        "data": data,
        }
    
    return render(request, "pub_priv_school_ls/list.html", context)

def int_schools(local_schools):
    for schools in local_schools:
        schools.kindergarten = int(schools.kindergarten)
        schools.kindergarten_male = int(schools.kindergarten_male)
        schools.kindergarten_female = int(schools.kindergarten_female)
            
        schools.first_grade = int(schools.first_grade)
        schools.first_grade_male = int(schools.first_grade_male)
        schools.first_grade_female = int(schools.first_grade_female)
            
        schools.second_grade = int(schools.second_grade)
        schools.second_grade_male = int(schools.second_grade_male)
        schools.second_grade_female = int(schools.second_grade_female)
            
        schools.third_grade = int(schools.third_grade)
        schools.third_grade_male = int(schools.third_grade_male)
        schools.third_grade_female = int(schools.third_grade_female)
            
        schools.fourth_grade = int(schools.fourth_grade)
        schools.fourth_grade_male = int(schools.fourth_grade_male)
        schools.fourth_grade_female = int(schools.fourth_grade_female)
            
        schools.fifth_grade = int(schools.fifth_grade)
        schools.fifth_grade_male = int(schools.fifth_grade_male)
        schools.fifth_grade_female = int(schools.fifth_grade_female)
            
        schools.sixth_grade = int(schools.sixth_grade)
        schools.sixth_grade_male = int(schools.sixth_grade_male)
        schools.sixth_grade_female = int(schools.sixth_grade_female)
            
        schools.seventh_grade = int(schools.seventh_grade)
        schools.seventh_grade_male = int(schools.seventh_grade_male)
        schools.seventh_grade_female = int(schools.seventh_grade_female)
            
        schools.eighth_grade = int(schools.eighth_grade)
        schools.eighth_grade_male = int(schools.eighth_grade_male)
        schools.eighth_grade_female = int(schools.eighth_grade_female)

pub_priv_school_ls/templates/pub_priv_school_ls/criteria.html
<html>
<body>

<h1>Input Longitude, Latitude and Radius</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
  
</form>

</body>
</html>

pub_priv_school_ls/templates/pub_priv_school_ls/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head> 
    <title> New Location</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'pub_priv_school_ls/css/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pub_priv_school_ls/css/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pub_priv_school_ls/css/form.css' %}">
</head>
<body>
<h1>
    <div class="box">
        <img class="logo" src="{% static 'pub_priv_school_ls/images/NL_logo_2.png' %}">
        <div class="title"> Market Tool</div> 
        <form method="post">
            {% csrf_token %}
            <button class="button" type="submit">New Location</button>
        </form>
    </div>
    
</h1>


<div class="dropdown">
    <button class="dropbtn">Select State</button> 
    <div class="dropdown-content">
            {% for loc in places%}
            <a href="{% url 'pub_priv_school_ls:area' loc %}">{{loc}}</a>
            {% endfor %}
    </div>
</div>

</body>
</html>

pub_priv_school_ls/templates/pub_priv_school_ls/state.html
<!DOCTYPE html>
{% load static %}
<html>
<head> 
    <title> New Location</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'pub_priv_school_ls/css/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pub_priv_school_ls/css/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pub_priv_school_ls/css/form.css' %}">
</head>
<body>
<h1>
    <div class="box">
        <img class="logo" src="{% static 'pub_priv_school_ls/images/NL_logo_2.png' %}">
        <div class="title"> Market Tool</div> 
        <form method="post">
            {% csrf_token %}
            <button class="button" type="submit">New Location</button>
        </form>
    </div>
    
</h1>

<div class="dropdown">
    <button class="dropbtn">{{ loc }}</button> 
    <div class="dropdown-content">
            {% for loc in places%}
            <a href="{% url 'pub_priv_school_ls:area' loc %}">{{loc}}</a>
            {% endfor %}
    </div>
</div>
<div>
    <form method="post">
        {% csrf_token %}
        <div class="box_for_form">
            <div class="flex_form">
                <label for="input_latitude">Input Latitude:</label>
                <input type="number" step=".000001" name="input_latitude" id="input_latitude" value="{{ form.input_latitude.value }}">
                
            </div>
            <div  class="flex_form">
                <label for="input_longitude">Input Longitude:</label>
                <input type="number" step=".000001" name="input_longitude" id="input_longitude" value="{{ form.input_longitude.value }}">
            </div>
            <div class="flex_form">
                <label for="radius">Radius (KM): </label>
                <input type="number" step=".01" name="radius" id="radius" value="{{ form.radius.value }}">
            </div>
            <div class="button_div">
                <input type="submit" class="submit_button" value="submit">
            </div>
        </div>
    </form>
</div>



</body>
</html>